version: '3'
networks:
  byfn:

services:

  kangyun-user-center:
    build: ./user/kangyun/kangyun-user-center
    container_name: kangyun-user-center
    ports:
      - 9992:9992
    networks:
      - byfn

## 注册节点
  consul1:
    image: consul:latest
    container_name: node1
    command: agent -server -bootstrap-expect=3 -node=node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    networks:
      - byfn

  consul2:
    image: consul:latest
    container_name: node2
    command: agent -server -retry-join=node1 -node=node2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
    networks:
      - byfn

  consul3:
    image: consul:latest
    container_name: node3
    command: agent -server -retry-join=node1 -node=node3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
    networks:
      - byfn

  consul4:
    image: consul:latest
    container_name: node4
    command: agent -retry-join=node1 -node=ndoe4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
      - 8500:8500
    depends_on:
      - consul2
      - consul3
    networks:
      - byfn
